# Generated by Django 4.1.6 on 2023-02-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_productitem_cart_id_alter_productitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='product_name',
            new_name='order_status',
        ),
    ]
